


@extends('layout.portal_layout')

@section('content')

    <!--build:css-->
    {{-- <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}"> --}}
    <div class="main">
        <section class="bg-no-repeat bg-center bg-cover h-[300px] lg:h-[10.4375em] md:h-[3em]" style="background-image: url({{ asset('assets/img/header-bg-5.jpg')}})">
            <div class="h-full bg-gradient-to-r from-[rgba(15,39,122,0.80)] to-[rgba(201,26,96,0.80)]">
                <div class="container mx-auto h-full flex items-center justify-center">
                    <div class="text-center">
                        <h1 class="text-4xl font-bold text-white">Terms & Conditions</h1>
                    </div>
                </div>
            </div>
        </section>
        <section class="pb-[50px] pt-[50px]" style="text-align: -webkit-center;">
            <h3 class="text-center text-[35px] font-semibold text-black pb-[30px]">Terms & Conditions </h3>
            <div class="text-left" style="width: 60%; ">
                <ul style="list-style: none;">
                        <li>
                            <span class="font-semibold">1. Introduction:</span> 
                            The purpose of the terms and conditions are outlining the rights, responsibilities, and obligations of both the company and its clients.
                        </li>
                        <li>
                            <span class="font-semibold">2. Company:</span> 
                            The Merilsoft will be in the lead and liable for deliveries to the client on behalf of its business partner or itself.
                        </li>
                        <li>
                            <span class="font-semibold">3. Scope of Work:</span> 
                            The services and solutions will be delivered as per the scope of works defined by the client within the company’s committed timeline.
                        </li>
                        <li>
                            <span class="font-semibold">4. Payment Terms:</span> 
                            The payment will be made by the client as upon the satisfactory delivery ofr the services and solutions. The payment methods can be in various legal forms.
                        </li>
                        <li>
                            <span class="font-semibold">5. Intellectual Property Rights:</span> 
                            The company will deserve the intellectual property right of the developed software in case the idea is generated by the company. Whereas the idea given by client be respected as the client’s intellectual property.
                        </li>
                        <li>
                            <span class="font-semibold">6. Confidentiality:</span> 
                            Both the company and the client will maintain the confidentiality of their developed software or solution, and communication.
                        </li>
                        <li>
                            <span class="font-semibold">7. Warranties and Liabilities:</span> 
                            Warranty period will be negotiated by both the parties.
                        </li>
                        <li>
                            <span class="font-semibold">8. Termination:</span> 
                            The contract or order can be terminated by either party in case of extreme level of situation by at least 30 days prior notice or any suitable duration.
                        </li>
                        <li>
                            <span class="font-semibold">9. Dispute Resolution:</span> 
                            In case of arise of any disputes, both the parties will engage the higher management on board to mitigate the issue.
                        </li>
                        <li>
                            <span class="font-semibold">10. Governing Law:</span> 
                            This Contract shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of law principles. The parties agree that any disputes arising out of or in connection with this Agreement shall be subject to the exclusive jurisdiction of the courts located in the State of New York.
                        </li>
                </ul>
            </div>
        </section>

        <section>
            <div class="bg-white shad py-3 mb-[25px] lg:py-6 lg:mb-[50px] mb-[25px]" style="margin-bottom:30px">
                <div class="container mx-auto px-2 lg:px-12 grid grid-cols-2 lg:grid-cols-7 justify-items-center gap-4 lg:gap-0  flex justify-center flex-col md:flex-col lg:flex-row" style="display: flex; gap: 50px;">
                    <div class="flex flex-col lg:flex-row items-center gap-3 lg:gap-6">
                        <img class="w-[3em] h-[3em] lg:w-[5.143125em] lg:h-[5.143125em]" src="./assets2/images/stats1.png" alt="image">
                        <div>
                            <h3 class="text-[16px] lg:text-3xl font-bold text-center lg:text-left" style="color: #1a2c79;font-size: 42px;">2500+</h3>
                            <h3 class="text-[12px] lg:text-[22px] font-semibold text-center lg:text-left">Projects</h3>
                        </div>
                    </div>
                    <div class="bg-primary w-px h-[4.5em] hidden lg:block"></div>
                    <div class="flex flex-col lg:flex-row items-center gap-3 lg:gap-6">
                        <img class="w-[3em] h-[3em] lg:w-[5.143125em] lg:h-[5.143125em]" src="./assets2/images/stats2.png" alt="image">
                        <div>
                            <h3 class="text-[16px] lg:text-3xl font-bold text-center lg:text-left" style="color: #1a2c79;font-size: 42px;">1500+</h3>
                            <h3 class="text-[12px] lg:text-[22px] font-semibold text-center lg:text-left">Happy Customers</h3>
                        </div>
                    </div>
                    <!-- <div class="bg-primary w-px h-[4.5em] hidden lg:block"></div>
                    <div class="flex flex-col lg:flex-row items-center gap-3 lg:gap-6">
                        <img class="w-[3em] h-[3em] lg:w-[4em] lg:h-[4em]" src="./assets2/images/stats3.png" alt="image">
                        <div>
                            <h3 class="text-[16px] lg:text-3xl font-bold text-center lg:text-left">7000+</h3>
                            <h3 class="text-[12px] lg:text-[22px] font-semibold text-center lg:text-left">Downloaded</h3>
                        </div>
                    </div> -->
                    <div class="bg-primary w-px h-[4.5em] hidden lg:block"></div>
                    <div class="flex flex-col lg:flex-row items-center gap-3 lg:gap-6">
                        <img class="w-[3em] h-[3em] lg:w-[4em] lg:h-[4em]" src="./assets2/images/stats4.png" alt="image">
                        <div>
                            <h3 class="text-[16px] lg:text-3xl font-bold text-center lg:text-left" style="color: #1a2c79;font-size: 42px;">100+</h3>
                            <h3 class="text-[12px] lg:text-[22px] font-semibold text-center lg:text-left">Team Members</h3>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- <div class="container mx-auto px-2 lg:px-12">
            <h3 class="font-semibold text-[16px] lg:text-[30px] leading-[37px] text-primary text-center pb-[25px] lg:pb-[47px]">Trusted by over 500+ customers<span style="font-size: 25px;">*</span>...</h3>
        </div> -->
    
        <div class="bg-[#F3F5FF]">
            <div  class="container mx-auto px-2 lg:px-12 grid grid-cols-2 lg:grid-cols-5 justify-items-center gap-4 lg:gap-0 py-5">
                <img class="w-[95px]" src="{{ asset('images/scout3.png') }}" alt="image">
                <img class="w-[85px]" src="{{ asset('images/bcct2.png') }}" alt="image">
                <img class="w-[87px]" src="{{ asset('images/govt3.png') }}" alt="image">
                <img class="w-[100px]" src="{{ asset('images/ict3.png') }}" alt="image">
                <img class="w-[75px]" src="{{ asset('images/a2i2.png') }}" alt="image">
            </div>
        </div>
    </div>


    <!--scroll bottom to top button end-->
    <!--build:js-->
    <script src="{{ asset('assets/js/vendors/jquery-3.5.1.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/popper.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/bootstrap.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/jquery.magnific-popup.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/jquery.easing.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/mixitup.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/headroom.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/smooth-scroll.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/wow.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/owl.carousel.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/jquery.waypoints.min.js')}}"></script>
    <!--<script src="{{ asset('assets/js/vendors/countUp.min.js')}}"></script>-->
    <script src="{{ asset('assets/js/vendors/jquery.countdown.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendors/validator.min.js')}}"></script>
    <script src="{{ asset('assets/js/app.js')}}"></script>
    <!--endbuild-->



    @endsection
